#!/usr/bin/with-contenv bash

if [ -z "$LOG_LEVEL" ]; then
      LOG_LEVEL=0
fi

if [ -z "$P2P_BIND_IP" ]; then
      P2P_BIND_IP=0.0.0.0
fi

if [ -z "$P2P_BIND_PORT" ]; then
      P2P_BIND_PORT=26967
fi

if [ -z "$RPC_BIND_IP" ]; then
      RPC_BIND_IP=127.0.0.1
fi

if [ -z "$RPC_BIND_PORT" ]; then
      RPC_BIND_PORT=26968
fi

if [ -z "$DAEMON_EXTRA_ARGS" ]; then
      DAEMON_EXTRA_ARGS=
fi

echo "Starting electronerod with:"
echo "  LOG_LEVEL:         $LOG_LEVEL"
echo "  P2P_BIND_IP:       $P2P_BIND_IP"
echo "  P2P_BIND_PORT:     $P2P_BIND_PORT"
echo "  RPC_BIND_IP:       $RPC_BIND_IP"
echo "  RPC_BIND_PORT:     $RPC_BIND_PORT"
echo "  DAEMON_EXTRA_ARGS: $DAEMON_EXTRA_ARGS"
echo ""

exec electronerod --log-level=$LOG_LEVEL --p2p-bind-ip=$P2P_BIND_IP --p2p-bind-port=$P2P_BIND_PORT --rpc-bind-ip=$RPC_BIND_IP --rpc-bind-port=$RPC_BIND_PORT --non-interactive $DAEMON_EXTRA_ARGS
